### ISSUE TITLE
chat resource not starting - yarn problem

### ISSUE THREAD

**Issue by sagaltsev** [routmoute/fxserver#22]
After starting environment with docker-compose chat is not starting. Manually invoking `start chat` crashes yarn.

**Comment by routmoute** [comment]
I don't know why that :
https://github.com/citizenfx/cfx-server-data/blob/44fc68d7ee1b94ad67a211a6ff8234ce4ff760c8/resources/%5Bsystem%5D/%5Bbuilders%5D/yarn/yarn_builder.js#L44
doesn't work, it start but permanently paused

**Comment by routmoute** [comment]
fixed here: b8603a08b129e2a0d68c6e5f22cb9ac5f7e758c6
