### ISSUE TITLE
Restarting the server crashes due to address already in use

### ISSUE THREAD

**Issue by zfmods** [routmoute/fxserver#26]
Trying to start the server or even restarting it leads to a crash with the following error code:

`Could not bind on 0.0.0.0:30120 - is this address valid and not already in use?`

Looks like having the FXServer as the entrypoint leads to that crash.

**Comment by routmoute** [comment]
Yes, indeed, it does it when I force the server's stop. The port remains blocked for a few minutes, I don't know why.

**Comment by routmoute** [comment]
google say it's an issue with docker desktop on windows (WSL2)

**Comment by zfmods** [comment]
No, I'm using your image in a Gitlab Pipeline to deploy the server in a Debian like distro. 

At last, I was able to launch the server and to perform restarts exposing the ports instead of binding them, I also added HaProxy to route the incoming connections.


    expose:
      - "30120/tcp"
      - "30120/udp"

**Comment by routmoute** [comment]
ok, thanks for the tip !
